### ISSUE TITLE
Aether is not thread safe

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-deployer#11]
"Out of the box, Aether provides nothing that helps to deal with concurrent access to a single local repository."
https://dev.eclipse.org/mhonarc/lists/aether-users/msg00312.html

We need to provide some solution to this. Above email thread links to https://github.com/takari/takari-local-repository.

**Comment by jvalkeal** [comment]
Not 100% if this trace relates to this:
```
16-06-28T10:55:49.59+0200 [APP/0]      OUT Caused by: java.io.FileNotFoundException: /home/vcap/.m2/repository/org/springframework/cloud/stream/app/twitterstream-source-rabbit/1.0.0.BUILD-SNAPSHOT/twitterstream-source-rabbit-1.0.0.BUILD-SNAPSHOT.jar.part.lock (No such file or directory)
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at java.io.RandomAccessFile.open0(Native Method) ~[na:1.8.0_91]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[na:1.8.0_91]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[na:1.8.0_91]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.eclipse.aether.connector.basic.PartialFile$LockFile.tryLock(PartialFile.java:123) ~[aether-connector-basic-1.0.2.v20150114.jar!/:na]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.eclipse.aether.connector.basic.PartialFile$LockFile.lock(PartialFile.java:71) ~[aether-connector-basic-1.0.2.v20150114.jar!/:na]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.eclipse.aether.connector.basic.PartialFile$LockFile.<init>(PartialFile.java:58) ~[aether-connector-basic-1.0.2.v20150114.jar!/:na]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.eclipse.aether.connector.basic.PartialFile$Factory.newInstance(PartialFile.java:210) ~[aether-connector-basic-1.0.2.v20150114.jar!/:na]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:432) ~[aether-connector-basic-1.0.2.v20150114.jar!/:na]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350) ~[aether-connector-basic-1.0.2.v20150114.jar!/:na]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     ... 86 common frames omitted
2016-06-28T10:55:49.58+0200 [APP/0]      OUT     at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.32.jar!/:8.0.32]
2016-06-28T10:55:49.59+0200 [APP/0]      OUT     at org.springframework.cloud.deployer.resource.maven.MavenArtifactResolver.resolve(MavenArtifactResolver.java:234) ~[spring-cloud-deployer-resource-maven-1.0.0.RC1.jar!/:1.0.0.RC1]
```
