### ISSUE TITLE
Resolving stream app artifact from http endpoint fails

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer#38]
As a user, I registered a stream application accessible at an `http` endpoint; however, when I use it in a stream, it fails with an error.

**registration:**
```
module register --name test-log --uri http://www.dropbox.com/<LOCATION>/log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar --type sink
```

**stream:**
```
stream create test --definition "time | test-log" --deploy
```

**error:**
```
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: java.io.FileNotFoundException: URL [http://www.dropbox.com/<LOCATION>/log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar] cannot be resolved to absolute file path because it does not reside in the file system: http://www.dropbox.com/<LOCATION>/log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar

java.io.FileNotFoundException: URL [http://www.dropbox.com/<LOCATION>/log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar] cannot be resolved to absolute file path because it does not reside in the file system: http://www.dropbox.com/<LOCATION>/log-sink-1.0.0.BUILD-SNAPSHOT-exec.jar

    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:52)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
    at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:357)
    at org.springframework.cloud.dataflow.rest.client.StreamTemplate.createStream(StreamTemplate.java:83)
    at org.springframework.cloud.dataflow.shell.command.StreamCommands.createStream(StreamCommands.java:99)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:57)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:130)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by jvalkeal** [comment]
Trouble is in `UrlResource` as actual exception is:
```
Caused by: java.io.FileNotFoundException: URL [http://repo.spring.io/libs-snapshot-local/org/springframework/cloud/stream/module/log-sink/1.0.0.BUILD-SNAPSHOT/log-sink-1.0.0.BUILD-20160408.122928-165-exec.jar] cannot be resolved to absolute file path because it does not reside in the file system: http://repo.spring.io/libs-snapshot-local/org/springframework/cloud/stream/module/log-sink/1.0.0.BUILD-SNAPSHOT/log-sink-1.0.0.BUILD-20160408.122928-165-exec.jar
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:218) ~[spring-core-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:52) ~[spring-core-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.core.io.UrlResource.getFile(UrlResource.java:212) ~[spring-core-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
```
`DefaultResourceLoader` fall back to using `URL`:
```
URL url = new URL(location);
return new UrlResource(url);
```
`UrlResource` doesn't work with `http` prefix if its `getFile()` method is called, however it should work with `getInputStream()`.

Why these work with  `MavenResources`? Well it resolves artifact to local repo and file is physically there and `getFile()` works which we use.

We need to use a `tmp` location where we copy these files from `getInputStream()` as shell needs access to physical file to read properties and it's a same thing with deployer. I was briefly thinking about this with yarn deployer where I copy resource artifact into hdfs. While artifact having `http://` and `maven://` may have same filename, they may physically be different files.

**Comment by sabbyanandan** [comment]
> We need to use a tmp location where we copy these files from getInputStream() as shell needs access to physical file to read properties and it's a same thing with deployer. 

I bumped into this issue while registering custom apps in PCF/pcfDEV. I didn't want to deal with remote maven repo etc. Having artifacts resolved via `http` would be very helpful for environments with no persistent volume support. This solution may not work for cloud environments.
